### ISSUE TITLE
can't build docker image

### ISSUE THREAD

**Issue by BrianOBlanton** [twosixlabs/Escalation#1]
MAC OSX, 10.15.6
Python3 from miniconda3

Tried to build the docker image, but get this error. 
docker-compose --verbose build                                                            

compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/Users/bblanton/.docker/config.json', '/Users/bblanton/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/bblanton/.docker/config.json
docker.utils.config.find_config_file: Trying paths: ['/Users/bblanton/.docker/config.json', '/Users/bblanton/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/bblanton/.docker/config.json
docker.auth.load_config: Found 'credsStore' section
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 727, in urlopen
  File "site-packages/urllib3/util/retry.py", line 403, in increment
  File "site-packages/urllib3/packages/six.py", line 734, in reraise
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "site-packages/docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 205, in _retrieve_server_version
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 228, in _get
  File "site-packages/requests/sessions.py", line 543, in get
  File "site-packages/requests/sessions.py", line 530, in request
  File "site-packages/requests/sessions.py", line 643, in send
  File "site-packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "site-packages/docker/api/client.py", line 188, in __init__
  File "site-packages/docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[78885] Failed to execute script docker-compose

**Comment by nleiby** [comment]
That sounds like your Docker daemon isn't running. 

You can check by running `docker ps -q`. You should get a response like `Error response from daemon: dial unix docker.raw.sock: connect: connection refused` if the Docker daemon isn't running.

Docker install and run instructions are here, if that is the case: https://docs.docker.com/docker-for-mac/install/

**Comment by BrianOBlanton** [comment]
That was it. Sorry about that. I'm just now spinning up on Docker...

**Comment by nleiby** [comment]
No worries- don't hesitate to reach out if you have issues.
